### ISSUE TITLE
Any ETA on Noise2D support?

### ISSUE THREAD

**Issue by bram-dingelstad** [memilian/libnoise#1]
I would love to use this library for a project I'm working on, however it depends on Noise2D support.
When do you think you can have Noise2D support implemented? If not, is there a quick hack to convert Noise3D to Noise2D?

Thank you for your time!

**Comment by memilian** [comment]
What feature from Noise2D do you need specifically ?
If you are looking to generate 2d noise, you can do it by passing 0 for the z coordinate in a module getValue function :  `var noiseValue = module.getValue(x,y,0)`
If you need to generate a 2D array of noise values, you can use a NoiseMap (see the NoiseMapBuilders section in the test file).
I guess the name is misleading, but Noise2D is just an utility class to generate a texture (and it's normal map) from a noise Module. The problem is that it's framework-specific, so it would need an implementation by framework.

**Comment by bram-dingelstad** [comment]
Oh jeez, yeah looks like I didn't really think to put a 0 in for z.
I guess I don't need Noise2D after all :/.
Amazing library you created tho, really helpful!
Thanks for your help anyway, appreciate it!
PS: I'm making planets https://i.imgur.com/jLqTHvd.png with your library
for a game https://96aa48.itch.io/ste I'm making, in case you were
wondering.
